### ISSUE TITLE
Tests crash when compiled with CMake and GCC on FreeBSD

### ISSUE THREAD

**Issue by vedranmiletic** [gabime/spdlog#1299]
```
Program received signal SIGSEGV, Segmentation fault.
0x00000008009bfa18 in vtable for __cxxabiv1::__si_class_type_info () from /lib/libcxxrt.so.1
(gdb) bt
#0  0x00000008009bfa18 in vtable for __cxxabiv1::__si_class_type_info () from /lib/libcxxrt.so.1
#1  0x0000000800eeed06 in __dynamic_cast () from /usr/local/lib/gcc9/libstdc++.so.6
#2  0x0000000800f7169e in bool std::has_facet<std::ctype<char> >(std::locale const&) () from /usr/local/lib/gcc9/libstdc++.so.6
#3  0x0000000800f63444 in std::basic_ios<char, std::char_traits<char> >::_M_cache_locale(std::locale const&) () from /usr/local/lib/gcc9/libstdc++.so.6
#4  0x0000000800f638e0 in std::basic_ios<char, std::char_traits<char> >::init(std::basic_streambuf<char, std::char_traits<char> >*) () from /usr/local/lib/gcc9/libstdc++.so.6
#5  0x0000000800f02d23 in std::ios_base::Init::Init() () from /usr/local/lib/gcc9/libstdc++.so.6
#6  0x0000000000446b7c in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /usr/local/lib/gcc9/include/c++/iostream:74
#7  0x00000000004470bf in _GLOBAL__sub_I_test_file_helper.cpp(void) () at ../tests/test_file_helper.cpp:100
#8  0x000000080081946e in ?? () from /libexec/ld-elf.so.1
#9  0x0000000000000000 in ?? ()
```

Swap CMake for Meson and it works fine. Swap GCC for Clang and it works fine. Any ideas?

**Comment by gabime** [comment]
Try to compare the compiler flags of Meson and CMake builds to find the what might have caused this.

**Comment by vedranmiletic** [comment]
Sorry, just figured out I enabled external fmt with CMake and disabled it with Meson. That's what's causing the crash.

**Comment by vedranmiletic** [comment]
> I've got the same crash: does it mean that external fmt and gcc don't play well on FreeBSD?

If external fmt was compiled with GCC, it should work fine.

**Comment by ytimenkov** [comment]
Thanks, for me or was other way around: I had to give up on gcc and use system clang (was no real reason to prefer gcc, just habit from Linux to have fresh compiler).
