### ISSUE TITLE
coredump at logger object destruct

### ISSUE THREAD

**Issue by deetchtoys** [gabime/spdlog#1350]
system: centos7

When logger object destruct, i met coredump.

Any problems with process fork? I create logger and then fork n processes.
 

```
(gdb) bt
#0  ~basic_memory_buffer (this=0x91, __in_chrg=<optimized out>) at /usr/local/include/spdlog/fmt/bundled/format.h:555
#1  ~log_msg_buffer (this=0x31, __in_chrg=<optimized out>) at /usr/local/include/spdlog/details/log_msg_buffer.h:14
#2  _Destroy<spdlog::details::log_msg_buffer> (__pointer=0x31) at /usr/include/c++/4.8.2/bits/stl_construct.h:93
#3  __destroy<spdlog::details::log_msg_buffer*> (__last=0x0, __first=0x31) at /usr/include/c++/4.8.2/bits/stl_construct.h:103
#4  _Destroy<spdlog::details::log_msg_buffer*> (__last=0x0, __first=0x31) at /usr/include/c++/4.8.2/bits/stl_construct.h:126
#5  _Destroy<spdlog::details::log_msg_buffer*, spdlog::details::log_msg_buffer> (__last=0x0, __first=0x31) at /usr/include/c++/4.8.2/bits/stl_construct.h:151
#6  ~vector (this=0x20708f8, __in_chrg=<optimized out>) at /usr/include/c++/4.8.2/bits/stl_vector.h:415
#7  ~circular_q (this=0x20708d8, __in_chrg=<optimized out>) at /usr/local/include/spdlog/details/circular_q.h:12
#8  ~backtracer (this=0x20708a8, __in_chrg=<optimized out>) at /usr/local/include/spdlog/details/backtracer.h:18
#9  spdlog::logger::~logger (this=0x2070858, __in_chrg=<optimized out>) at /usr/local/include/spdlog/logger.h:68
#10 0x00007f1f3132eae9 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x2070840) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:144
#11 0x00007f1f310ce0d4 in CMTCNN::~CMTCNN() () from /lib64/libfaceDetectorSDK.so
```

**Comment by gabime** [comment]
please provide example to reproduce

**Comment by deetchtoys** [comment]
Two shared libraries use different version of spdlog cause this problem.

Thank you.
