### ISSUE TITLE
MemorySanitizer: use-of-uninitialized-value

### ISSUE THREAD

**Issue by saturnairjam** [gabime/spdlog#1550]
When invoking the default logger, I see this issue when my code is instrumented with MemorySanitizer:

```
Uninitialized bytes in __interceptor_fwrite at offset 1 inside [0x716000000280, 9)
==18450==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x704767 in spdlog::sinks::ansicolor_sink<spdlog::details::console_mutex>::print_ccode_(fmt::v6::basic_string_view<char> const&) External/spdlog/include/spdlog/sinks/ansicolor_sink-inl.h:115:5
    #1 0x704767 in spdlog::sinks::ansicolor_sink<spdlog::details::console_mutex>::log(spdlog::details::log_msg const&) External/spdlog/include/spdlog/sinks/ansicolor_sink-inl.h:55:9
    #2 0x6c9c68 in spdlog::logger::sink_it_(spdlog::details::log_msg const&) External/spdlog/include/spdlog/logger-inl.h:186:23
    #3 0x6c9a87 in spdlog::logger::log_it_(spdlog::details::log_msg const&, bool, bool) External/spdlog/include/spdlog/logger-inl.h:170:9
    #4 0x535344 in void spdlog::logger::log<char [5]>(spdlog::source_loc, spdlog::level::level_enum, fmt::v6::basic_string_view<char>, char const (&) [5]) External/spdlog/include/spdlog/logger.h:90:13
    #5 0x52a1eb in void spdlog::logger::log<char [5]>(spdlog::level::level_enum, fmt::v6::basic_string_view<char>, char const (&) [5]) External/spdlog/include/spdlog/logger.h:98:9
    #6 0x52a1eb in void spdlog::logger::error<char [5]>(fmt::v6::basic_string_view<char>, char const (&) [5]) External/spdlog/include/spdlog/logger.h:128:9
    #7 0x52a1eb in void spdlog::error<char [5]>(fmt::v6::basic_string_view<char>, char const (&) [5]) External/spdlog/include/spdlog/spdlog.h:163:27


SUMMARY: MemorySanitizer: use-of-uninitialized-value External/spdlog/include/spdlog/sinks/ansicolor_sink-inl.h:115:5 in spdlog::sinks::ansicolor_sink<spdlog::details::console_mutex>::print_ccode_(fmt::v6::basic_string_view<char> const&)
Exiting
```

**Comment by gabime** [comment]
which version are you using? There been a fix about it few days ago.

**Comment by saturnairjam** [comment]
I'm using 1.6.0.

**Comment by gabime** [comment]
Which commit are you using ?

**Comment by saturnairjam** [comment]
https://github.com/gabime/spdlog/tree/5ca5cbd44739576ee90d3d9c21ba8cbf7e11ff5c

Yes, I think you're right. I had reached a similar conclusion.
