### ISSUE TITLE
core dump with qt_sink.

### ISSUE THREAD

**Issue by WorstCodeWay** [gabime/spdlog#2148]
Hi, all. First, I'd say this project is really great and I rely on it very much in my work. Thanks for your great work.

I'm develop a application in Qt, and I want to develop a log window based on `spdlog`. The log window will print all logs from different modules. Sorry for not being able to supply a minimal program(I have tried to but it's more complicated than I thought), but this time I meet `core dump` here:

> free(): invalid pointer

I should say reasons of `core dump` vary. I have meet `double free or corruption (out)`, `corrupted size vs. prev_size` and `free(): invalid pointer` here.

Here is the trace:
```bash
(gdb) bt
#0  0x00007ffff5297fb7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff5299921 in __GI_abort () at abort.c:79
#2  0x00007ffff52e2967 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff540fb0d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff52e99da in malloc_printerr (str=str@entry=0x7ffff540dd08 "free(): invalid pointer") at malloc.c:5342
#4  0x00007ffff52f0f0c in _int_free (have_lock=0, p=0x555557b857f0, av=0x7ffff5644c40 <main_arena>) at malloc.c:4167
#5  0x00007ffff52f0f0c in __GI___libc_free (mem=0x555557b85800) at malloc.c:3134
#6  0x00005555555d017f in LogArea::ShowLog(QString) ()
#7  0x00005555555aaa29 in LogArea::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#8  0x00007ffff5e93771 in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const (this=this@entry=0x7fffffffc558, object=0x5555581e0fd0, 
    object@entry=0x7fffffffc5d0, connectionType=Qt::DirectConnection, 
    connectionType@entry=Qt::AutoConnection, returnValue=..., val0=..., val1=..., val2=..., val3=..., val4=..., val5=..., val6=..., val7=..., val8=..., val9=...) at kernel/qmetaobject.cpp:2303
#9  0x00007ffff5e98718 in QMetaObject::invokeMethod(QObject*, char const*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) (obj=0x7fffffffc5d0, member=0x0, type=Qt::AutoConnection, ret=..., val0=..., val1=..., val2=..., val3=..., val4=..., val5=..., val6=..., val7=..., val8=..., val9=...) at kernel/qmetaobject.cpp:1516
#10 0x00007ffff7866206 in spdlog::sinks::qt_sink<std::mutex>::sink_it_(spdlog::details::log_msg const&) () at /home/jason/Documents/vist/vistrack-new/VisTrackStudio/lib/libVisTrackCore.so
#11 0x00007ffff78d9d0a in spdlog::sinks::base_sink<std::mutex>::log(spdlog::details::log_msg const&) () at /home/jason/Documents/vist/vistrack-new/VisTrackStudio/lib/libVisTrackCore.so
#12 0x00005555555b3b65 in spdlog::logger::sink_it_(spdlog::details::log_msg const&) ()
#13 0x00005555555fd7e6 in spdlog::logger::log_it_(spdlog::details::log_msg const&, bool, bool) ()
#14 0x00007ffff78a9118 in void spdlog::logger::log_<int>(spdlog::source_loc, spdlog::level::level_enum, fmt::v8::basic_string_view<char>, int&&) ()
    at /home/jason/Documents/vist/vistrack-new/VisTrackStudio/lib/libVisTrackCore.so
#15 0x00007fffae9bf22d in QtPrivate::QFunctorSlotObject<PendantDetectVist::Init()::{lambda()#2}, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
    at /home/jason/Documents/vist/vistrack-new/VisTrackStudio/vistrackers/processors/pendantdetectproc/libpendantdetectproc_vist.so
#16 0x00007ffff5ebf810 in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7fffffffcdf0, r=0x555557a929f0, this=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:398
#17 0x00007ffff5ebf810 in doActivate<false>(QObject*, int, void**) (sender=0x555557a63d10, signal_index=7, argv=0x7fffffffcdf0) at kernel/qobject.cpp:3886
#18 0x00007ffff5ebf810 in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7fffffffcee0, r=0x555557a63d10, this=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:398
#19 0x00007ffff5ebf810 in doActivate<false>(QObject*, int, void**) (sender=0x555557a63990, signal_index=8, argv=0x7fffffffcee0) at kernel/qobject.cpp:3886
#20 0x00007ffff7895271 in RoiEditor::mouseReleaseEvent(QMouseEvent*) () at /home/jason/Documents/vist/vistrack-new/VisTrackStudio/lib/libVisTrackCore.so
#21 0x00007ffff6eb36d0 in QWidget::event(QEvent*) (this=0x555557a63990, event=0x7fffffffd370) at kernel/qwidget.cpp:9019
#22 0x00007ffff6e753cc in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x555557a63990, e=0x7fffffffd370) at kernel/qapplication.cpp:3630
#23 0x00007ffff6e7c188 in QApplication::notify(QObject*, QEvent*) (this=<optimized out>, receiver=0x555557a63990, e=0x7fffffffd370) at kernel/qapplication.cpp:3074
#24 0x00007ffff5e870e8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x555557a63990, event=0x7fffffffd370) at kernel/qcoreapplication.cpp:1063
#25 0x00007ffff5e872ae in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) (receiver=receiver@entry=0x555557a63990, event=event@entry=0x7fffffffd370) at kernel/qcoreapplication.cpp:1470
#26 0x00007ffff6e7b4ca in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) (receiver=receiver@entry=0x555557a63990, event=event@entry=
    0x7fffffffd370, alienWidget=alienWidget@entry=0x555557a63990, nativeWidget=0x555557a63d10, buttonDown=buttonDown@entry=0x7ffff7573a90 <qt_button_down>, lastMouseReceiver=..., spontaneous=true, onlyDispatchEnterLeave=false) at kernel/qapplication.cpp:2614
#27 0x00007ffff6eccf78 in QWidgetWindow::handleMouseEvent(QMouseEvent*) (this=this@entry=0x555557b66ec0, event=event@entry=0x7fffffffd740) at kernel/qwidgetwindow.cpp:684
#28 0x00007ffff6ecfc83 in QWidgetWindow::event(QEvent*) (this=0x555557b66ec0, event=0x7fffffffd740) at kernel/qwidgetwindow.cpp:300
#29 0x00007ffff6e753cc in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x555557b66ec0, e=0x7fffffffd740) at kernel/qapplication.cpp:3630
#30 0x00007ffff6e7beb0 in QApplication::notify(QObject*, QEvent*) (this=<optimized out>, receiver=0x555557b66ec0, e=0x7fffffffd740) at kernel/qapplication.cpp:3376
#31 0x00007ffff5e870e8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x555557b66ec0, event=0x7fffffffd740) at kernel/qcoreapplication.cpp:1063
#32 0x00007ffff5e872ae in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) (receiver=receiver@entry=0x555557b66ec0, event=event@entry=0x7fffffffd740) at kernel/qcoreapplication.cpp:1470
#33 0x00007ffff65506d6 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) (e=0x555557b767b0) at kernel/qguiapplication.cpp:2277
#34 0x00007ffff6551ae5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) (e=e@entry=0x555557b767b0) at kernel/qguiapplication.cpp:2002
#35 0x00007ffff652d8cb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) (flags=..., flags@entry=...) at kernel/qwindowsysteminterface.cpp:1175
#36 0x00007fffe346057a in xcbSourceDispatch(GSource*, GSourceFunc, gpointer) (source=<optimized out>) at qxcbeventdispatcher.cpp:105
#37 0x00007fffef61d537 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007fffef61d770 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007fffef61d7fc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#40 0x00007ffff5ee2aac in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x555555a90ef0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#41 0x00007ffff5e85afa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffdac0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:232
---Type <return> to continue, or q <return> to quit---
#42 0x00007ffff5e8eab3 in QCoreApplication::exec() () at kernel/qcoreapplication.cpp:1371
#43 0x00005555555a7db0 in main ()
```

And some related codes:
#15 in trace is the lambda, its definition as:
```c++
  _imageEditor = new ImagePlanarRoi;
  connect(_imageEditor, &ImagePlanarRoi::itemUpdated, this, [&](){
    _rois.clear();
    _imageEditor->GetAllNormalizedEntities(_rois);
    if(logger) logger->info("Roi changed. Size is {}.", _rois.size());
  });
```
And the log view widget is LogArea (inherits from `QTextEdit`)
```c++
void LogArea::ShowLog(QString msg)
{
  QString level = msg.section("[", 1, 1).section("]", 0, 0);
  if(level.startsWith("E"))
  {
    setTextColor(_erroColor);
  }
  else if(level.startsWith("W"))
  {
    setTextColor(_warnColor);
  }
  else if(level.startsWith("I"))
  {
    setTextColor(_infoColor);
  }
  else if(level.startsWith("D"))
  {
    setTextColor(_debgColor);
  }
  append(msg);
}
```

I don't know what the reason is, or even how to debug it.
Please help.

**Comment by gabime** [comment]
@WorstCodeWay whats the status if this issue?
