### ISSUE TITLE
spdlog stuck at mutex_lock

### ISSUE THREAD

**Issue by Kur0x** [gabime/spdlog#847]
I use signal to do some inter-process communication. But process always got stuck. I check the stack as follows. **I used spdlog in the signal handler, it seems to be the cause of the problem.**
```
#2  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:133
#3  0x00007fec077b2dbd in __GI___pthread_mutex_lock (mutex=0x75b260 <spdlog::details::console_mutex::mutex()::s_mutex>) at ../nptl/pthread_mutex_lock.c:80
#4  0x0000000000491679 in __gthread_mutex_lock(pthread_mutex_t*) ()
#5  0x0000000000496606 in std::mutex::lock() ()
#6  0x000000000049c51e in std::lock_guard<std::mutex>::lock_guard(std::mutex&) ()
#7  0x00000000004ccb41 in spdlog::sinks::ansicolor_sink<spdlog::details::console_stdout, spdlog::details::console_mutex>::log(spdlog::details::log_msg const&) ()
#8  0x000000000049a150 in spdlog::logger::sink_it_(spdlog::details::log_msg const&) ()
#9  0x00000000004ae684 in void spdlog::logger::log<>(spdlog::level::level_enum, char const*) ()
#10 0x00007fec064c09c9 in void spdlog::logger::debug<>(char const*) () from xxx.so
#11 0x00007fec064adf95 in handler(int) () from xxx.so
#12 <signal handler called>
#13 0x00007fec0563d2dd in write () at ../sysdeps/unix/syscall-template.S:84
#14 0x00007fec055bebff in _IO_new_file_write (f=0x7fec0590b620 <_IO_2_1_stdout_>, data=0x1a649b0, n=57) at fileops.c:1263
#15 0x00007fec055c0409 in new_do_write (to_do=57,
    data=0x1a649b0 "[2018-09-27 22:28:25.356] [0] [\033[36mdebug\033[m] waiting...\nZcopyDone/kill 1\n 96\n96 8\ntRank\n", ' ' <repeats 36 times>, "\t....\n...\n00016 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 \t........."..., fp=0x7fec0590b620 <_IO_2_1_stdout_>) at fileops.c:518
#16 _IO_new_do_write (fp=0x7fec0590b620 <_IO_2_1_stdout_>,
    data=0x1a649b0 "[2018-09-27 22:28:25.356] [0] [\033[36mdebug\033[m] waiting...\nZcopyDone/kill 1\n 96\n96 8\ntRank\n", ' ' <repeats 36 times>, "\t....\n...\n00016 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 \t........."..., to_do=57) at fileops.c:494
#17 0x00007fec055bf47d in _IO_new_file_xsputn (f=0x7fec0590b620 <_IO_2_1_stdout_>, data=<optimized out>, n=13) at fileops.c:1331
#18 0x00007fec055b47bb in __GI__IO_fwrite (buf=0x7fffb22be034, size=1, count=13, fp=0x7fec0590b620 <_IO_2_1_stdout_>) at iofwrite.c:39
#19 0x00000000004cd414 in spdlog::sinks::ansicolor_sink<spdlog::details::console_stdout, spdlog::details::console_mutex>::print_range_(fmt::v5::basic_memory_buffer<char, 500ul, std::allocator<char> > const&, unsigned long, unsigned long) ()
#20 0x00000000004ccccc in spdlog::sinks::ansicolor_sink<spdlog::details::console_stdout, spdlog::details::console_mutex>::log(spdlog::details::log_msg const&) ()
#21 0x000000000049a150 in spdlog::logger::sink_it_(spdlog::details::log_msg const&) ()
#22 0x00000000004ae684 in void spdlog::logger::log<>(spdlog::level::level_enum, char const*) ()
#23 0x00007fec064c09c9 in void spdlog::logger::debug<>(char const*) () from xxx.so
```

**Comment by gabime** [comment]
mutex and signal handlers do no interact well (
https://www.linuxquestions.org/questions/programming-9/locking-mutex-in-a-signal-handler-function-789218) .
Try using dedicated single threaded(_st) logger inside signal handlers.
